---
driver:
  name: vagrant

platforms:
<% %w(ubuntu-14.04 centos-7.0).each do |os| %w(11.8.2 12.0.3).each do |chef_version| %>
  - name: <%= os %>_chef-<%= chef_version %>
    driver_config:
      box: opscode_<%= os %>
      require_chef_omnibus: <%= chef_version %>
<% end end %>

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[influxdb::default]
    attributes:
      influxdb:
        action: [create,start]